FROM oven/bun:1.2-alpine AS deps

WORKDIR /www
COPY . .

RUN bun install --frozen-lockfile

WORKDIR /www/apps/api

RUN bun prisma generate --schema ./src/database/schema
RUN bun prisma db push --schema ./src/database/schema

FROM oven/bun:1.2-alpine AS runner

ENV APP_HOST=0.0.0.0
ENV APP_PORT=8080

COPY --from=deps /www/node_modules ./node_modules
COPY --from=deps /www/apps/api .

EXPOSE 8080

CMD ["bun", "run", "dev"]